# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{roundersrecipes}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francois Harbec"]
  s.date = %q{2011-06-16}
  s.description = %q{Rounders recipes for Capistrano}
  s.email = %q{fharbec@gmail.com}
  s.files = [
    "Rakefile",
    "VERSION",
    "lib/roundersrecipes/linode2.rb",
    "roundersrecipes.gemspec",
    "templates/database_yml.erb",
    "templates/nginx.erb"
  ]
  s.homepage = %q{http://github.com/rounders/roundersrecipes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Rounders recipes for Capistrano}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.5.0", "<= 2.9.0"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.5.0", "<= 2.9.0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.5.0", "<= 2.9.0"])
  end
end

